# Practica de Algebra lineal

### *Nombre*: miguel cores

<span style="color:blue">Ejercicio 1:  
Usando los procedimientos add y mult_vector_escalar definidos anteriormente, calcular:   
{$\alpha$[1,2]+[3,4] : $\alpha$$\in$$\mathbb{R}$, 0$\leq$$\alpha$$\leq$1, con una precision de dos decimales (para la multiplicación)}</style>

In [4]:
import numpy as np

In [35]:
#def addn(v,w):
    #return[v[i]+w[i] for i in range(len(v))]

def mult_vector_escalar(alpha,v):   
    return [alpha*v[i] for i in range(len(v))]

#def calculo(alpha,v,w):
    #a='alpha debe estar en el intervalo indicado'
    #return addn(mult_vector_escalar(alpha,v), w) if 0<=alpha<=1 else a

#print("introduzca el valor de alpha que quiera:")
#alpha=input()

def add(v,w):
    return [v[0]+w[0],v[1]+w[1]]
    
m=[add(mult_vector_escalar(float(i/100),[float(1),float(2)]),[3,4]) for i in range(101)]

m

#calculo(alpha,[1,2],[3,4])

[[3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],
 [3.0, 4.0],

<span style="color:red"> Queríamos calcularlo para todos los $\alpha$, no para uno en concreto:  
def add(v,w):  
    return [v[0]+w[0],v[1]+w[1]]  
def mult_vector_escalar(alpha,v):  
    return [alpha*v[i] for i in range(len(v))]  
[add(mult_vector_escalar(i/100,[1,2]),[3,4]) for i in range(101)]</style>

<span style="color:blue">Ejercicio 2:  
Mortadelo y Filemón usan como clave el siguiente vector:</style>  
> <span style="color:blue">**k**=[0,1,0,0,1,0,1,0,1,0]</style>  

<span style="color:blue">Mortadelo quiere enviarle a Filemón el siguiente mensaje:</style>  
> <span style="color:blue">**p**=[0,0,0,1,1,1,0,1,0,1]</style>  

<span style="color:blue">Mortadelo encripta su mensaje añadiendo k:</style>  
> <span style="color:blue">**c**=**p**+**k**=[0,0,0,1,1,1,0,1,0,1]+[0,1,0,0,1,0,1,0,1,0]=[0,1,0,1,0,1,1,1,1,1]</style>  

<span style="color:blue">Cuando Filemón recibe el mensaje, lo desencripta añadiendo **k** a lo que ha recibido</style>  
> <span style="color:blue">**p**=**c**+**k**=[0,1,0,1,0,1,1,1,1,1]+[0,1,0,0,1,0,1,0,1,0]=[0,0,0,1,1,1,0,1,0,1]</style>    

<span style="color:blue">que es el mensaje original</style>    
  
 <span style="color:blue">¿Cómo lo harías en Python? (Definiendo un procedimiento)</style>  

In [65]:
k=[0,1,0,0,1,0,1,0,1,0]
p=[0,0,0,1,1,1,0,1,0,1]
c=[0,1,0,1,0,1,1,1,1,1]

def suma_gf2(m,n):
    l=addn(m,n)
    for i in range(len(l)):
        if ((l[i]==0) | (l[i]==2)):
            l[i]=0
        else:
            l[i]=1
    return l

suma_gf2(c,k)

[0, 0, 0, 1, 1, 1, 0, 1, 0, 1]

<span style="color:blue">Ejercicio 3: coste total o beneficio. </style>

<span style="color:blue">Supongamos que D es el conjunto de algunos ingredientes de la cerveza: </style>
> <span style="color:blue">D={lúpulo, malta, agua, levadura}</style>  

<span style="color:blue">Por otro lado tenemos el vector coste:</style>  
> <span style="color:blue">coste={lúpulo: 2,5€, malta: 1.5€, agua: 0.006€, levadura: 0,45€}</style>  

<span style="color:blue">Por último tenemos el vector cantidad con lo necesario para hacer una cerveza:</style>  
> <span style="color:blue">cantidad={lúpulo: 6u, malta: 14u, agua: 7u, levadura: 11u}</style>  

<span style="color:blue">¿Cuánto cuesta hacer una cerveza?</style> 

In [21]:
def producto_escalar(u,v):
    return sum(u[i]*v[i] for i in range(len(v)))

coste = [2.5, 1.5,.006,.45]
cantidad = [6,14,7,11]
coste_cerveza = producto_escalar(coste,cantidad)

"el coste de la cerveza sera: "+str(coste_cerveza)+" euros"

'el coste de la cerveza sera: 40.992 euros'

<span style="color:blue"> Ejercicio 4:   
¿Cómo escribirías cada uno de los vectores {[3,0,0],[0,2,0],[0,0,1]} como combinación lineal de {[2,0,1],[1,0,2],[2,2,2]}?
Escribe las combinaciones lineales en Python. Seguramente tenga que definir una nueva suma.</style>

In [62]:
A = np.matrix([
    [2,0,1],
    [1,0,2],
    [2,2,2]
])

B = np.matrix(
    [[3],
     [0],
     [0]]
)

X = np.linalg.solve(A, B)
X

matrix([[ 2.],
        [-1.],
        [-1.]])

In [64]:
A = np.matrix([
    [2,0,1],
    [1,0,2],
    [2,2,2]
])

B = np.matrix(
    [[0],
     [2],
     [0]]
)

X = np.linalg.solve(A, B)
X

matrix([[-0.66666667],
        [-0.66666667],
        [ 1.33333333]])

In [63]:
A = np.matrix([
    [2,0,1],
    [1,0,2],
    [2,2,2]
])

B = np.matrix(
    [[2],
     [2],
     [2]]
)

X = np.linalg.solve(A, B)
X

matrix([[ 0.66666667],
        [-0.33333333],
        [ 0.66666667]])

<span style="color:blue"> Ejercicio 5:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [74]:
A=np.matrix([
    [2,-3],
    [-4,6]
])
B=np.matrix([
    [8,4],
    [5,5]
])
C=np.matrix([
    [5,-2],
    [3,1]
])
A*B==A*C

matrix([[ True,  True],
        [ True,  True]], dtype=bool)

In [75]:
B==C

matrix([[False, False],
        [False, False]], dtype=bool)

<span style="color:blue"> Ejercicio 6 :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

In [82]:
A=np.matrix([
    [3,-6],
    [-1,2]
])

B=np.matrix([
    [2,-4],
    [1,-2]
])

A*B

matrix([[0, 0],
        [0, 0]])

<span style="color:blue"> Ejercicio 7:  
Sarrus para el determinante de orden 3.  
¿Cómo lo haríamos en Python?</style>

In [56]:
A=np.matrix([
    [1,2,3],
    [3,2,1],
    [4,5,6]
])

In [9]:
A=np.matrix([
[1,-4,2],
[-2,8,-9],
[-1,7,0]
])
x = 0
y = 0
for i in range (0,3):
    
    x = x + (A[0,i])*(A[1,(i+1)%3])*(A[2,(i+2)%3])
    y = y + (A[2,i])*(A[1,(i+1)%3])*(A[0,(i+2)%3])
print ("Determinante = ", x-y)

('Determinante = ', 15)


<span style="color:blue"> Ejercicio 8:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [9]:
M=np.matrix([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
])
np.linalg.matrix_rank(M)

3

In [5]:
'Al tener rango 3 y el sistema tendra una unica solucion'

'Al tener rango 3 y el sistema tendra una unica solucion'

> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [10]:
M=np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])
np.linalg.matrix_rank(M)

2

In [11]:
M=np.matrix([
    [8,1,-4],
    [1,-3,2],
    [1,-8,7]
])
np.linalg.matrix_rank(M)

3

In [13]:
'Al tener la ampliada rango 3 y M rango 2 el sistema no tendra solucion'

'Al tener la ampliada rango 3 y M rango 2 el sistema no tendra solucion'

> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [14]:
M=np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])
np.linalg.matrix_rank(M)

2

In [17]:
M_1=np.matrix([
    [1,0,2],
    [2,3,3],
    [3,3,5]
])
np.linalg.matrix_rank(M_1)

2

In [18]:
M_2=np.matrix([
    [2,0,1],
    [3,3,1],
    [5,3,2]
])
np.linalg.matrix_rank(M_2)

2

M_3=np.matrix([
    [1,2,1],
    [2,3,1],
    [3,5,2]
])
np.linalg.matrix_rank(M_3)

In [20]:
'Como la ampliada y M tienen igual rango 2 que es menor que el numero de variables el sistema tendra infinito numero de soluciones'

'Como la ampliada y M tienen igual rango 2 que es menor que el numero de variables el sistema tendra infinito numero de soluciones'

<span style="color:blue"> Ejercicio 9:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

<span style="color:black"> r([x , y ]) = M ∗ [x , y ] con $
  M =
  \left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]
$.  
Luego r(x,y)=(xcos$\theta$-xsin$\theta$,ysin$\theta$+ycos$\theta$)</style> 
* <span style="color:black">r($\alpha$x,$\alpha$y)=($\alpha$xcos$\theta$-$\alpha$xsin$\theta$,$\alpha$ysin$\theta$+$\alpha$ycos$\theta$)=$\alpha$((xcos$\theta$-xsin$\theta$,ysin$\theta$+ycos$\theta$)=$\alpha$r(x,y)</style>  
* <span style="color:black">r[(x<sub>1</sub>,y<sub>1</sub>),(x<sub>2</sub>,y<sub>2</sub>)]=r(x<sub>1</sub>+x<sub>2</sub>,y<sub>1</sub>+y<sub>2</sub>)=[(x<sub>1</sub>+x<sub>2</sub>)cos$\theta$-(x<sub>1</sub>+x<sub>2</sub>)sin$\theta$,(y<sub>1</sub>+y<sub>2</sub>)sin$\theta$+(y<sub>1</sub>+y<sub>2</sub>)cos$\theta$]=(x<sub>1</sub>cos$\theta$+x<sub>2</sub>cos$\theta$-x<sub>1</sub>sin$\theta$-x<sub>2</sub>sin$\theta$,y<sub>1</sub>sin$\theta$+y<sub>2</sub>sin$\theta$+y<sub>1</sub>cos$\theta$+y<sub>2</sub>cos$\theta$)=(x<sub>1</sub>cos$\theta$-x<sub>1</sub>sin$\theta$,y<sub>1</sub>sin$\theta$+y<sub>1</sub>cos$\theta$) +(x<sub>2</sub>cos$\theta$-x<sub>2</sub>sin$\theta$,y<sub>2</sub>sin$\theta$+y<sub>2</sub>cos$\theta$)=r(x<sub>1</sub>,y<sub>1</sub>)+r(x<sub>2</sub>,y<sub>2</sub>) </style>  

In [51]:
'vamos a hacer la prueba para un angulo O=90º, que tendria por M la siguiente matriz'
M=np.matrix([
    [round(np.cos(np.pi/2)),round(np.sin(np.pi/2))],
    [round(-np.sin(np.pi/2)),round(np.cos(np.pi/2))]
])
v=np.matrix([
    [1],
    [2]
])
u=np.matrix([
    [3],
    [3]
])
M

matrix([[ 0.,  1.],
        [-1.,  0.]])

Comprobamos 1a propiedad: r(α(x,y)) = αf((x,y)), donde r(x,y)=M*[x,y] y [x,y]=v

In [48]:
2*M*v==M*(2*v)

matrix([[ True],
        [ True]], dtype=bool)

Comprobamos 2a propiedad r (u + v) = r (u) + r (v), donde v y r igual que antes y u = [3,3]

In [53]:
u_v=u+v
M*u_v == M*u + M*v

matrix([[ True],
        [ True]], dtype=bool)

<span style="color:blue"> Ejercicio 10:  
¿Cuál es la representación coordenada del vector v= [6, 3, 2, 5] en términos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1]?</style> 

In [11]:
A=np.matrix([
[2, 1, 0],
[2, 0, 1],
[2, -1, 0],
[3, 0, 1]
])
B=np.matrix([
[6],
[3],
[2],
[5]
])
C=np.linalg.lstsq(A,B)[0]
print("La representación de v en términos de los vectores dados es {}".format(np.transpose(C)))
A*C

La representación de v en términos de los vectores dados es [[ 2.  2. -1.]]


matrix([[ 6.],
        [ 3.],
        [ 2.],
        [ 5.]])

<span style="color:blue"> Ejercicio 11:  
Supongamos que queremos diseñar la red de internet para el otro campus universitario.  
La red debe lograr la misma conectividad que el grafo de entrada.  
Una arista representa un posible cable.  
El peso de la arista es el coste de instalar el cable.  
Nuestro objetivo es minimizar el coste total, usando el algoritmo Grow y el algoritmo Shrink.  </style> 

'Algoritmo de grow' 


'Consideramos cada camino de forma ascendente: Bio-Med.Pembroke Campus, Pembroke Cmapus.Athletic Complex, Athletic Complex.Bio-Med' 

'Concluimos que la red tiene que ser: Bio-Med.Pembroke Campus, Pembroke Campus.Athletic Complex'

'Algoritmo de Shrink'

'Quitamos de forma descendiente y queda el mismo resultado nada mas quitar la arista de mas peso'

<span style="color:blue"> Ejercicio 12:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$. Calcular el rango por filas y por columnas usando Python.</style> 

In [122]:
M=([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])
rangoM=np.linalg.matrix_rank(M)
rangoM

3

In [123]:
MT=np.transpose(M)
rangoMT=np.linalg.matrix_rank(MT)
rangoMT

3

<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

<span style="color:blue"> Ejercicio 14:  
Modificar lo necesario en los algoritmos para que funcionen y calculen el problema de la casa en llamas.</style>

In [2]:
import numpy as np

def p_e(a,b):
    return float(sum(sum(a*b)))

def proyeccion_paralela(b, a):
    sigma = p_e(b,a)/p_e(a,a) if (p_e(a,a) > 10^-20) else 0
    return [sigma * a[i] for i in range(len(a))]

def proyeccion_ortogonal(b, a):
    return b - proyeccion_paralela(b, a)

a=np.array([
    [6,2]
])
b=np.array([
    [2,4]
])

proyeccion_ortogonal(b,a)

array([[-1.,  3.]])